version: "3.8"
services:
  location-recommendation-redis:
    container_name: location-recommendation-redis
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: khm052678/location-recommendation-redis
    ports:
      - "6379:6379"
  location-recommendation-database:
    container_name: location-recommendation-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: khm052678/location-recommendation-database
    environment:
      - MARIADB_DATABASE=location-recommendation
      - MARIADB_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
    - ./database/config:/etc/mysql/conf.d
    - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
