version: "3.8"                                          # 파일 규격 버전
services:                                               # 이 항목 밑에 실행하려는 컨테이너들을 정의
  location-recommendation-redis:                        # 서비스명
    container_name: location-recommendation-redis       # 컨테이너 명
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: khm052678/location-recommendation-redis
    ports:
      - "6379:6379"
  location-recommendation-database:
    container_name: location-recommendation-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: khm052678/location-recommendation-database
    environment:
      - MARIADB_DATABASE=location-recommendation
      - MARIADB_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./database/config:/etc/mysql/conf.d
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"      # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
  location-recommendation-app:
    container_name: location-recommendation-app
    build: .
    depends_on:          # DB, REDIS 컨테이너가 실행된 다음 WEB을 실행
      - location-recommendation-database
      - location-recommendation-redis
    image: khm052678/location-recommendation-app
    environment:
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - KAKAO_REST_API_KEY=${KAKAO_REST_API_KEY}
    ports:
      - "80:8080"
    restart: always
